name: Deploy Static Files to S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust based on the version you need

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is present

      - name: ⚙️ Run collectstatic
        run: |
          python Backend/manage.py collectstatic --noinput

      - name: Deploy to S3 bucket
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
# This line is what deploys the single page React web app to S3 
        run: aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
